package JavaRevision_Package1;

public class Java_18_10_FinallyAndCatch2 {

	public static void main(String[] args) {
		System.out.println("A");
		try{
		int i=9/3;
		}
		catch(Exception e){
			System.out.println("some exception is coming...");
		}
		finally{
			System.out.println("run this line..");
		}
		

	}

}
